name: Docker Image CI

concurrency: production

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag p7-Kasa:$(date +%s)
  
  deployment:
    runs-on: p7-Kasa:latest
